[tool.black]
line-length = 79
target-version = ['py311']
extend-exclude = '''
/(
  \.git
  | \.venv
  | notebooks
  | data
)/
'''

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"
addopts = "-v --cov=src --cov-report=term"

[tool.coverage.run]
source = ["src"]
omit = ["*/tests/*", "*/notebooks/*", "*/data/*"]
